[book]
title = "算法学习"
authors = ["TickPoints"]
description = "为中文开发者提供的算法导论 Rust 实现(工作中...)"
language = "zh-CN"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-alerts.css"]
preferred-dark-theme = "mocha"
default-theme = "latte"
additional-js = [
  "./theme/scripts/mermaid.min.js",
  "./theme/scripts/init.js",
]
edit-url-template = "https://github.com/tickpoints/algorithm_learning/edit/main/{path}"
git-repository-url = "https://github.com/tickpoints/algorithm_learning"
git-repository-icon = "fab-github"
input-404 = "not-found.md"

[preprocessor.katex]
# 使用katex
after = ["links"]

[preprocessor.mermaid]
# 使用mermaid
command = "mdbook-mermaid"

[preprocessor.alerts]
# 使用alerts

[preprocessor.betterlink]
# 使用betterlink
display_processed_contents = false
use_old_tag_adder = false
